# Generated by Django 5.2 on 2025-05-01 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('date_livraison_prevue', models.DateField(verbose_name='Date de livraison prévue')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('recue', 'Reçue'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('facture', models.CharField(blank=True, max_length=100, verbose_name='Numéro de facture')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant payé')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': "Commande d'Achat",
                'verbose_name_plural': "Commandes d'Achat",
            },
        ),
        migrations.CreateModel(
            name='ArticleAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit', verbose_name='Produit')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achats.commandeachat', verbose_name='Commande')),
            ],
            options={
                'verbose_name': "Article d'Achat",
                'verbose_name_plural': "Articles d'Achat",
            },
        ),
    ]
