# Generated by Django 5.2.1 on 2025-05-25 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
        ('produits', '0003_alter_produit_unite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandeachat',
            options={'ordering': ['-date_commande'], 'verbose_name': "Commande d'Achat", 'verbose_name_plural': "Commandes d'Achat"},
        ),
        migrations.RemoveField(
            model_name='commandeachat',
            name='date_livraison_prevue',
        ),
        migrations.AlterField(
            model_name='articleachat',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='achats.commandeachat'),
        ),
        migrations.AlterField(
            model_name='articleachat',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='articleachat',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit'),
        ),
        migrations.AlterField(
            model_name='articleachat',
            name='quantite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='facture',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='fournisseur',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='montant_paye',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=50),
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.CharField(blank=True, max_length=200)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-date_achat'],
            },
        ),
    ]
