# Generated by Django 5.2.1 on 2025-05-25 18:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('produits', '0003_alter_produit_unite'),
        ('ventes', '0002_alter_vente_options_alter_articlevente_prix_unitaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlevente',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, help_text='Prix unitaire du produit en FCFA', max_digits=10),
        ),
        migrations.AlterField(
            model_name='articlevente',
            name='produit',
            field=models.ForeignKey(help_text='Produit vendu', on_delete=django.db.models.deletion.CASCADE, to='produits.produit'),
        ),
        migrations.AlterField(
            model_name='articlevente',
            name='quantite',
            field=models.IntegerField(help_text='Quantité vendue (doit être positive)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='articlevente',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remise appliquée en pourcentage (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='articlevente',
            name='vente',
            field=models.ForeignKey(help_text='Vente associée à cet article', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='ventes.vente'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client associé à la vente (facultatif)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_clients', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateTimeField(auto_now_add=True, help_text='Date et heure de la vente'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='est_credit',
            field=models.BooleanField(default=False, help_text='Indique si la vente est à crédit'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Montant total de la vente (calculé automatiquement)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vente',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taux de TVA appliqué (en %)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='vente',
            name='utilisateur',
            field=models.ForeignKey(help_text='Utilisateur ayant effectué la vente', on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to=settings.AUTH_USER_MODEL),
        ),
    ]
