# Generated by Django 5.2 on 2025-05-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('vendeur', 'Vendeur'), ('magasinier', 'Magasinier'), ('comptable', 'Comptable')], default='utilisateur', max_length=20, verbose_name='Rôle'),
        ),
    ]
