# Generated by Django 5.2.1 on 2025-05-25 18:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('produits', '0003_alter_produit_unite'),
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant de la dépense en FCFA', max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la dépense')),
                ('description', models.TextField(blank=True, help_text='Description de la dépense (facultatif)')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, help_text='Date de la dernière mise à jour du stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='emplacement',
            field=models.CharField(blank=True, default='Entrepôt Principal', help_text='Emplacement du stock', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantite',
            field=models.IntegerField(help_text='Quantité en stock (doit être positive)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='seuil_critique',
            field=models.IntegerField(default=10, help_text='Seuil minimum avant alerte de stock faible'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client associé à la vente (facultatif)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_ventes', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateTimeField(auto_now_add=True, help_text='Date et heure de la vente'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, help_text='Prix unitaire de la vente en FCFA', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vente',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_rapports', to='produits.produit'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='quantite',
            field=models.IntegerField(help_text='Quantité vendue (doit être positive)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
