# Generated by Django 5.2 on 2025-05-01 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotureCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cloture', models.DateTimeField(auto_now_add=True, verbose_name='Date de clôture')),
                ('solde_ouverture', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Solde d'ouverture")),
                ('solde_cloture', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solde de clôture')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Clôture de Caisse',
                'verbose_name_plural': 'Clôtures de Caisse',
            },
        ),
        migrations.CreateModel(
            name='TransactionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10, verbose_name='Type de transaction')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transaction de Caisse',
                'verbose_name_plural': 'Transactions de Caisse',
            },
        ),
    ]
