# Generated by Django 5.2 on 2025-05-01 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('seuil_critique', models.PositiveIntegerField(default=10, verbose_name='Seuil critique')),
                ('emplacement', models.CharField(blank=True, max_length=100, verbose_name='Emplacement')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('transfert', 'Transfert')], max_length=20, verbose_name='Type de mouvement')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Mouvement de Stock',
                'verbose_name_plural': 'Mouvements de Stock',
            },
        ),
    ]
