# Generated by Django 5.2 on 2025-05-01 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_alter_produit_options'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouvementstock',
            options={'ordering': ['-date_mouvement'], 'verbose_name': 'Mouvement de Stock', 'verbose_name_plural': 'Mouvements de Stock'},
        ),
        migrations.RenameField(
            model_name='mouvementstock',
            old_name='date_creation',
            new_name='date_mouvement',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date_modification',
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='produits.produit'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='raison',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='emplacement',
            field=models.CharField(blank=True, default='Entrepôt Principal', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='produits.produit'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='seuil_critique',
            field=models.IntegerField(default=10),
        ),
    ]
