# Generated by Django 5.2.1 on 2025-05-25 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_alter_produit_unite'),
        ('stocks', '0002_alter_mouvementstock_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvementstock',
            name='raison',
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='produits.produit'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
