# Generated by Django 5.2 on 2025-05-01 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('unite', models.CharField(choices=[('piece', 'Pièce'), ('boite', 'Boîte'), ('kg', 'Kilogramme'), ('litre', 'Litre')], max_length=20, verbose_name='Unité')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat")),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('prix_gros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de gros')),
                ('remise', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Remise')),
                ('reference_fournisseur', models.CharField(blank=True, max_length=100, verbose_name='Référence fournisseur')),
                ('code_barres', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Code-barres')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
    ]
