# Generated by Django 5.2.1 on 2025-05-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_alter_produit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='unite',
            field=models.CharField(choices=[('piece', 'Pièce'), ('metre', 'Mètre'), ('kg', 'Kilogramme'), ('litre', 'Litre')], max_length=20, verbose_name='Unité'),
        ),
    ]
